-- =====================================================================
-- Dev Admin seed (user_id = 1) — real loginable account.
--
--   Email:    dev@realestate360.local
--   Password: Demo@1234
--   Role:     ADMIN  (role_id = 1)
--
-- The password_hash below is a real BCryptPasswordEncoder hash (cost=10)
-- of "Demo@1234". It was generated by iam-service's own encoder, so
-- AuthService.login() round-trips correctly.
--
-- Why this file exists:
--   * /auth/dev-token mints JWTs but never inserts a user row. When a
--     downstream service writes to audit_logs (which has a hard FK to
--     users.user_id), the insert fails with ERROR 1452 unless that user
--     row already exists.
--   * Before this update the seed used a placeholder hash so password
--     login was impossible; you had to mint dev-tokens out-of-band.
--     The real hash here lets you sign in to the SPA at
--     http://localhost:5173 directly.
--
-- Run this once per fresh database, then dev-tokens for userId=1 work
-- end-to-end through gateway -> service -> compliance audit fan-out,
-- AND password login via /api/v1/iam/auth/login also works.
--
-- Idempotent: re-running is safe and silent (MySQL 8 aliased syntax).
-- Connect as root because audit-related grants are scoped.
-- =====================================================================

USE realestate3601;

-- Step 1: Insert / refresh the dev admin user (idempotent).
INSERT INTO users
    (user_id, uuid, full_name, email, password_hash, status)
VALUES
    (1, 'aaaaaaaa-0000-0000-0000-000000000001',
     'Dev Admin', 'dev@realestate360.local',
     '$2a$10$U0eR.TvooI6/jHuBO3et3uoZ3Fu7kMvVGug/YYZlViblHyFg5liSS', 'ACTIVE') AS new_row
ON DUPLICATE KEY UPDATE
    full_name     = new_row.full_name,
    email         = new_row.email,
    password_hash = new_row.password_hash,
    status        = new_row.status;

-- Step 2: Assign the ADMIN role (role_id = 1) to user_id = 1 (idempotent).
INSERT INTO user_roles
    (user_id, role_id)
VALUES
    (1, 1) AS new_row
ON DUPLICATE KEY UPDATE
    role_id = new_row.role_id;

-- Step 3: Sanity checks — must return one row each.
SELECT user_id, email, status FROM users WHERE user_id = 1;
SELECT ur.user_id, ur.role_id, r.name AS role_name
FROM user_roles ur
JOIN roles r ON r.role_id = ur.role_id
WHERE ur.user_id = 1;
